### ISSUE TITLE
Remove usage of LocationSpan::todo()

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#396]
`LocationSpan::todo` is a placeholder and should eventually removed.

- [ ] lib/skc_ast2hir/src/convert_exprs
- [ ] lib/skc_ast2hir/src/hir_maker
- [ ] lib/skc_ast2hir/src/pattern_match
- [ ] lib/skc_ast2hir/src/lib.rs
